name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

      - name: Build project
        run: bun run build

      - name: Check for build artifacts
        run: |
          if [ -d ".next" ]; then
            echo "✅ Build successful - .next directory created"
            ls -la .next/
          else
            echo "❌ Build failed - .next directory not found"
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run type check
        run: bunx tsc --noEmit

      - name: Verify build works
        run: bun run build

      - name: Test production build
        run: |
          bun run build
          bun run start &
          sleep 10
          curl -f http://localhost:3000 || exit 1
          pkill -f "bun run start"
